### ISSUE TITLE
Using remote plugin version but got "[coc.nvim] Command: fzf-preview.Initialized not found" when opening Neovim

### ISSUE THREAD

**Issue by judewang** [yuki-yano/fzf-preview.vim#226]
## Problems summary

I'm using the remote plugin version of this plugin, but still got coc relative error message when opening Neovim.

```
[coc.nvim] Command: fzf-preview.Initialized not found
```

### Expected

No coc-fzf-preview error messages when opening Neovim with remote plugin version of fzf-preview.

### Environment Information

- fzf-preview version (package.json): `2.0.7`

- OS: macOS 11.0.1 Big Sur with M1 chip

- Vim/Neovim version: `v0.5.0-dev+b535575`

### Provide a minimal init.vim

```vim
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'yuki-ycino/fzf-preview.vim', { 'branch': 'release/remote', 'do': ':UpdateRemotePlugins' }
call plug#end() 
```

### Screenshot

![CleanShot 2021-01-18 at 11 35 57](https://user-images.githubusercontent.com/1559819/104866219-5a906d80-5981-11eb-8e0a-66a66f8bba6d.png)

**Comment by yuki-yano** [comment]
Due to a recent coc specification change, there is a problem that fzf-preview.Initialized will be executed if CocCommandAsync exists.
Is it possible to use the coc version?

If it's difficult to use the coc version, I'll consider fixing it.

**Comment by judewang** [comment]
@yuki-ycino Hi, thank you for replying. I've tried using the coc version, but I cannot install coc-fzf-preview successfully. Have no idea was it a conflict issue of M1 chip or node `v15.5.1`. I got this:

```
 Download progress 94.0%
 Download progress 97.3%
 Download progress 100.0%
 Extension download at /var/folders/_d/1yhg4jj132dggzhky6910zvm0000gn/T/nvimm2GUYx/coc-fzf-
 preview-4f0L44
 Installing dependencies by: /Users/jude/.nvm/versions/node/v15.5.1/bin/node install --ignore-
 scripts --no-lockfile --production.
 node:internal/modules/cjs/loader:928
   throw err;
   ^

 Error: Cannot find module '/private/var/folders/_d/1yhg4jj132dggzhky6910zvm0000gn/T/nvimm2GUYx/
 coc-fzf-preview-4f0L44/install'
     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
     at node:internal/main/run_main_module:17:47 {
   code: 'MODULE_NOT_FOUND',
   requireStack: []
 }
 /Users/jude/.nvm/versions/node/v15.5.1/bin/node install exited with 1
```

**Comment by yuki-yano** [comment]
Fixed in e0fbe3e629f8bdda0e499237843a0df319bede07.
Please try it.

**Comment by judewang** [comment]
@yuki-ycino The issue has been fixed after updating to v2.0.8. Thank you for your help.
